array_width = 100
attr_fn_like_width = 100
chain_width = 100
edition = "2018"
fn_call_width = 100
fn_cell_width = 100
ignore = [
    # "src/some_file.rs",    # example
]
match_block_trailing_comma = true
max_width = 100
reorder_imports = true
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# unstable
brace_style = "PreferSameLine"
combine_control_expr = true
comment_width = 100
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
fn_single_line = true
format_doc_comments = true
format_generated_files = true
format_macro_matchers = true
format_strings = true
#license_template_path = "// Copyright {\d+} The Rust Project Developers." # example
match_arm_blocks = false
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 20
wrap_comments = true
